version: '2.4'
services:
    mysql:
      image: mysql:5.7
      container_name: browser-chat-mysql
      env_file:
        - .env
      ports:
        - "3306:3306"
      healthcheck:
        test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
        interval: 5s
        timeout: 10s
        retries: 3

    rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: browser-chat-rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      healthcheck:
        test: [ "CMD", "nc", "-z", "localhost", "5672" ]
        interval: 10s
        timeout: 10s
        retries: 3

    chat-api:
      build:
        context: .
        dockerfile: build/chat-api/Dockerfile
      container_name: chat-api
      env_file:
        - .env
      ports:
        - "80:80"
      links:
        - "mysql:mysql"
        - "rabbitmq:rabbitmq"
      depends_on:
        mysql:
          condition: service_healthy
        rabbitmq:
          condition: service_healthy

    chat-bot:
      build:
        context: .
        dockerfile: build/chat-bot/Dockerfile
      container_name: chat-bot
      env_file:
        - .env
      links:
        - "rabbitmq:rabbitmq"
      depends_on:
        rabbitmq:
          condition: service_healthy